_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
import numpy as np

# Create array
arr = np.array([10, 4, 7, 20, 15, -9, 33])

# Print array
print("Array:", arr)

# Find maximum and minimum
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))


Array: [10  4  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [ ]:
def find_maximum(arr):
    if not arr:
        return None

    max_value = arr[0]

    for element in arr[1:]:
        if element > max_value:
            max_value = element

    return max_value

user_array = []
print("Enter numbers one by one. Type 'done' when you are finished.")

while True:
    user_input = input("Enter a number: ")
    if user_input.lower() == 'done':
        break
    try:
        number = float(user_input)
        user_array.append(number)
    except ValueError:
        print("Invalid input. Please enter a valid number or 'done'.")

result = find_maximum(user_array)

if result is not None:
    print("\nThe elements you entered are:", user_array)
    print("The maximum value in the array is:", result)

Enter numbers one by one. Type 'done' when you are finished.


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [1]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 4], [6, 8]])

# Sum of matrices
sum_matrix = A + B

# Subtraction of matrices
sub_matrix = A - B

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Sum of matrices:\n", sum_matrix)
print("Subtraction of matrices:\n", sub_matrix)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 4]
 [6 8]]
Sum of matrices:
 [[ 3  6]
 [ 9 12]]
Subtraction of matrices:
 [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [2]:
import numpy as np

initial_matrix = np.random.randint(0, 100, size=(5, 6))

print("Original 5x6 Matrix:")
print(initial_matrix)
print("-" * 30)

new_row = np.random.randint(0, 100, size=(1, 6))
updated_matrix = np.vstack([initial_matrix, new_row])

print("Matrix with new row added:")
print(updated_matrix)
print("-" * 30)

print("Sum of each row:")
for i, row in enumerate(updated_matrix):
    row_sum = np.sum(row)
    print(f"Sum of Row {i + 1}: {row_sum}")


Original 5x6 Matrix:
[[38 90 79  4 41 66]
 [38 77 62  1 60 27]
 [49 36 19 30 79  3]
 [58 40 41 39 15 15]
 [83 35 89  3 13 61]]
------------------------------
Matrix with new row added:
[[38 90 79  4 41 66]
 [38 77 62  1 60 27]
 [49 36 19 30 79  3]
 [58 40 41 39 15 15]
 [83 35 89  3 13 61]
 [64 48 60 54 18 42]]
------------------------------
Sum of each row:
Sum of Row 1: 318
Sum of Row 2: 265
Sum of Row 3: 216
Sum of Row 4: 208
Sum of Row 5: 284
Sum of Row 6: 286


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [3]:
import numpy as np

original_matrix = np.random.randint(low=0, high=10, size=(5, 6))

extra_column = np.random.randint(low=0, high=10, size=(5, 1))

matrix_with_extra_column = np.hstack([original_matrix, extra_column])

sine_matrix = np.sin(matrix_with_extra_column)

print("Matrix after adding one column (shape {}):\n".format(matrix_with_extra_column.shape), matrix_with_extra_column)
print("\nSine of each element (same shape):\n", sine_matrix)


Matrix after adding one column (shape (5, 7)):
 [[8 8 9 9 1 1 4]
 [8 2 8 3 8 1 6]
 [0 0 6 0 7 4 3]
 [1 4 1 8 4 9 1]
 [3 2 1 6 2 3 5]]

Sine of each element (same shape):
 [[ 0.98935825  0.98935825  0.41211849  0.41211849  0.84147098  0.84147098
  -0.7568025 ]
 [ 0.98935825  0.90929743  0.98935825  0.14112001  0.98935825  0.84147098
  -0.2794155 ]
 [ 0.          0.         -0.2794155   0.          0.6569866  -0.7568025
   0.14112001]
 [ 0.84147098 -0.7568025   0.84147098  0.98935825 -0.7568025   0.41211849
   0.84147098]
 [ 0.14112001  0.90929743  0.84147098 -0.2794155   0.90929743  0.14112001
  -0.95892427]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [4]:
import numpy as np

matrix = np.random.randint(0, 10, (5, 6))
result = matrix[2:4, 1:4]

print("Original Matrix:\n", matrix)
print("\nSliced Matrix:\n", result)


Original Matrix:
 [[5 5 9 4 0 5]
 [2 2 4 1 4 9]
 [7 4 0 9 0 1]
 [5 4 2 6 7 8]
 [8 7 3 6 2 4]]

Sliced Matrix:
 [[4 0 9]
 [4 2 6]]


### Great Job!